Add genre director profile views and react router
mdillemuth/fightFlix-client pull request #4
Opened 2020-12-03 03:00 UTC by mdillemuth

I have a few problems so far with this branch and I believe they are mainly about the 'user' state. 

![add-director-view-genre-view](https://user-images.githubusercontent.com/67530427/100957826-310ea600-34e9-11eb-9206-3785a8210862.gif)

**Things that work**
- Registering a new account
- Removing an account
- Logging in
- Logging out
- Displaying favorites in profile view
- Removing a favorite from profile view
- Displaying movies with same director in director view
- Displaying movies with same genre in genre view

**Things that DONT work**
- The moviecards sometimes do not load immediately after logging in, this is shown in the gif
- Updating account information from profile view
- Refreshing the page while in profile view 
- Immediately updating the user's favorites after removing a favorite while in profile view

2020-12-03 13:34 UTC, eadsimone requested changes

2020-12-03 13:34 UTC, eadsimone commented on src/components/profile-view/profile-view.jsx
> +
`
componentDidMount() {
		const accessToken = localStorage.getItem('token');
		if (accessToken !== null) {
			this.getUser(accessToken);
		}
	}`

	getUser(token) {
		const username = localStorage.getItem('user');
		axios
			.get(`https://bchanmyflix.herokuapp.com/users/${username}`, {
				headers: { Authorization: `Bearer ${token}` },
			})
			.then((response) => {
				this.setState({
					Username: response.data.Username,
					Password: response.data.Password,
					Email: response.data.Email,
					Birthday: response.data.Birthday,
					FavoriteMovies: response.data.FavoriteMovies,
				});
			})
			.catch(function (error) {
				console.log(error);
			});
	}

2020-12-03 13:34 UTC, eadsimone commented on src/components/main-view/main-view.jsx
> +  };
this.getMovies(authData.token);

2020-12-12 15:19 UTC, mdillemuth commented
![3-5-gif-final](https://user-images.githubusercontent.com/67530427/101987303-47430180-3c61-11eb-9fab-885a1bf022e5.gif)

**Major Changes**
- Client-side authentication that prevents submitting invalid forms to the server
- Server-side authentication that alerts the user when the received form was invalid (ex. username taken)
- Redirecting from invalid URLs to a '/not-found' page
- Code refactoring and abstracting components to clean-up project
  - Separate components for registration form and login form
  - Separate component for displaying favorites in profileView (favoritesView)
  - Separate component for displaying movies 
-----
**Minor Changes**
  - Added favicon
  - Added customized loading spinner gif for when form is submitted to display while waiting for server response
  - NavBar is abstracted to render on all routes, but profile/logout buttons only render when user after user is logged in

2020-12-12 15:46 UTC, eadsimone approved these changes
![urock](https://user-images.githubusercontent.com/2244503/101988388-04d8ef00-3c78-11eb-88cf-09f01290ce93.gif)

2020-12-12 15:46 UTC, eadsimone commented on src/components/movie-view/movie-view.jsx
> +                  <i className='star fa fa-star-o text-warning'></i>
for favorites you can something like:
```
<div className="favorites-button-container">
								<Button className="movie-view-button favorites-button" value={movie._id} onClick={(e) => this.handleAddFavorite(e, movie)}>
									Add to Favorites
								</Button>
							</div>
```

2020-12-12 15:46 UTC, eadsimone commented on src/components/movie-view/movie-view.jsx
```
handleAddFavorite(e, movie) {
		e.preventDefault();
		const username = localStorage.getItem('user');
		const token = localStorage.getItem('token');
		axios({
			method: 'post',
			url: `https://bchanmyflix.herokuapp.com/users/${username}/Movies/${movie._id}`,
			headers: { Authorization: `Bearer ${token}` },
		})
			.then(() => {
				alert(`${movie.Title} was add to Favorites`);
			})
			.catch(function (err) {
				console.log(err);
			});
	}
```

2020-12-14 15:17 UTC, merged